### ISSUE TITLE
Separate "log in" and "sign up" buttons

### ISSUE THREAD

**Issue by nathanmsmith** [hotseatio/hotseat.io#48]

**Comment by nathanmsmith** [comment]
<img width="1369" alt="CleanShot 2023-01-22 at 16 13 05@2x" src="https://user-images.githubusercontent.com/5677971/213948043-84f16cd3-bc3b-4c2d-84ed-8920fabf5602.png">

**Comment by lzhou0714** [comment]
Should we just have a single button that tells them to signup/login using their UCLA Single Sign On, since both the sign up and register would lead to the same page anyway?

**Comment by nathanmsmith** [comment]
I'll leave that up to you @lzhou0714! Feel free to try both. "Log in with SSO" is a little long and may be confusing to some users though. Open to better wordings.

**Comment by lzhou0714** [comment]
Alternatively, we can have a line of small text above that tells them to login with their UCLA email and then just have a login button? I have it implemented right now as a login and a sign up that both redirect to SSO.

**Comment by nathanmsmith** [comment]
I think let's go with the separate "Log in" and "Sign up" buttons. I want to avoid extra text if possible – users don't like to read small text! I think it's totally fine that they direct to the same place but if it's confusing we can change.

**Comment by nathanmsmith** [comment]
Closed by #53
